#reporter_engine
import os
import json
import logging
import tempfile
import shutil
from datetime import datetime
from typing import Dict, List, Optional, Union

logging.basicConfig(level=logging.INFO, format='[%(levelname)s] %(message)s')
logger = logging.getLogger(__name__)

# Report format templates
MARKDOWN_TEMPLATE = """# NetMan Security Report

**Generated:** {timestamp}
**Target Scope:** {scope}
**Report Version:** {version}

## Executive Summary

This report contains findings from NetMan security analysis including passive skimmer detections and AI-powered vulnerability insights.

## Skimmer Findings

{skimmer_section}

## AI Analysis Summary

{ai_section}

## Technical Details

- **Analysis Duration:** {duration}
- **Total Findings:** {total_findings}
- **High Risk Items:** {high_risk}

---
*Report generated by NetMan v{version}*
"""

HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
    <title>NetMan Security Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
        .header {{ background: #f0f0f0; padding: 20px; border-radius: 5px; }}
        .section {{ margin: 20px 0; }}
        .finding {{ background: #ffebee; padding: 10px; margin: 5px 0; border-left: 4px solid #f44336; }}
        .safe {{ background: #e8f5e8; padding: 10px; margin: 5px 0; border-left: 4px solid #4caf50; }}
        .metadata {{ font-size: 0.9em; color: #666; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>NetMan Security Report</h1>
        <p class="metadata">
            Generated: {timestamp}<br>
            Target Scope: {scope}<br>
            Version: {version}
        </p>
    </div>

    <div class="section">
        <h2>Skimmer Findings</h2>
        {skimmer_html}
    </div>

    <div class="section">
        <h2>AI Analysis Summary</h2>
        <pre>{ai_insights}</pre>
    </div>

    <div class="section">
        <h3>Statistics</h3>
        <ul>
            <li>Analysis Duration: {duration}</li>
            <li>Total Findings: {total_findings}</li>
            <li>High Risk Items: {high_risk}</li>
        </ul>
    </div>
</body>
</html>"""

def _validate_inputs(scope: str, skimmer_hits: List[str], ai_insights: str) -> bool:
    """Validate report input parameters."""
    if not isinstance(scope, str):
        logger.error("Scope must be a string")
        return False
    if not isinstance(skimmer_hits, list):
        logger.error("Skimmer hits must be a list")
        return False
    if not isinstance(ai_insights, str):
        logger.error("AI insights must be a string")
        return False
    return True

def _format_skimmer_section(skimmer_hits: List[str]) -> str:
    """Format skimmer findings for markdown."""
    if not skimmer_hits:
        return "No passive leaks detected."
    return "\n".join(f"* {hit}" for hit in skimmer_hits)

def _format_skimmer_html(skimmer_hits: List[str]) -> str:
    """Format skimmer findings for HTML."""
    if not skimmer_hits:
        return '<div class="safe">No passive leaks detected.</div>'
    return "\n".join(f'<div class="finding">{hit}</div>' for hit in skimmer_hits)

def _calculate_stats(skimmer_hits: List[str], ai_insights: str) -> Dict[str, Union[int, str]]:
    """Calculate report statistics."""
    total_findings = len(skimmer_hits)
    # Simple heuristic for high-risk items (contains sensitive keywords)
    high_risk_keywords = ['password', 'token', 'key', 'secret', 'credit', 'ssn']
    high_risk = sum(1 for hit in skimmer_hits
                   if any(keyword in hit.lower() for keyword in high_risk_keywords))
    return {
        'total_findings': total_findings,
        'high_risk': high_risk,
        'duration': 'N/A',  # Could be enhanced to track actual duration
    }

def generate_report_text(scope: str, skimmer_hits: Optional[List[str]] = None,
                        ai_insights: str = "", version: str = "1.0") -> str:
    """Generate a markdown security report.

    Args:
        scope: Target scope/domain
        skimmer_hits: List of skimmer findings
        ai_insights: AI analysis summary
        version: Report version

    Returns:
        Formatted markdown report
    """
    if not _validate_inputs(scope, skimmer_hits or [], ai_insights):
        return ""

    skimmer_hits = skimmer_hits or []
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    stats = _calculate_stats(skimmer_hits, ai_insights)

    skimmer_section = _format_skimmer_section(skimmer_hits)

    report = MARKDOWN_TEMPLATE.format(
        timestamp=timestamp,
        scope=scope,
        version=version,
        skimmer_section=skimmer_section,
        ai_section=ai_insights or "No AI analysis performed.",
        **stats
    )

    logger.info(f"Generated markdown report for scope: {scope}")
    return report

def generate_report_html(scope: str, skimmer_hits: Optional[List[str]] = None,
                        ai_insights: str = "", version: str = "1.0") -> str:
    """Generate an HTML security report.

    Args:
        scope: Target scope/domain
        skimmer_hits: List of skimmer findings
        ai_insights: AI analysis summary
        version: Report version

    Returns:
        Formatted HTML report
    """
    if not _validate_inputs(scope, skimmer_hits or [], ai_insights):
        return ""

    skimmer_hits = skimmer_hits or []
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    stats = _calculate_stats(skimmer_hits, ai_insights)

    skimmer_html = _format_skimmer_html(skimmer_hits)

    report = HTML_TEMPLATE.format(
        timestamp=timestamp,
        scope=scope,
        version=version,
        skimmer_html=skimmer_html,
        ai_insights=ai_insights or "No AI analysis performed.",
        **stats
    )

    logger.info(f"Generated HTML report for scope: {scope}")
    return report

def generate_report_json(scope: str, skimmer_hits: Optional[List[str]] = None,
                        ai_insights: str = "", version: str = "1.0") -> str:
    """Generate a JSON security report.

    Args:
        scope: Target scope/domain
        skimmer_hits: List of skimmer findings
        ai_insights: AI analysis summary
        version: Report version

    Returns:
        JSON formatted report
    """
    if not _validate_inputs(scope, skimmer_hits or [], ai_insights):
        return "{}"

    skimmer_hits = skimmer_hits or []
    stats = _calculate_stats(skimmer_hits, ai_insights)

    report_data = {
        "metadata": {
            "generated": datetime.now().isoformat(),
            "scope": scope,
            "version": version,
            "generator": "NetMan"
        },
        "findings": {
            "skimmer_hits": skimmer_hits,
            "ai_insights": ai_insights
        },
        "statistics": stats
    }

    try:
        json_report = json.dumps(report_data, indent=2)
        logger.info(f"Generated JSON report for scope: {scope}")
        return json_report
    except Exception as e:
        logger.error(f"Failed to generate JSON report: {e}")
        return "{}"

def save_report(file_path: str, report_text: str) -> tuple[bool, str]:
    """Save report to file atomically.

    Args:
        file_path: Target file path
        report_text: Report content

    Returns:
        Tuple of (success, message)
    """
    if not file_path:
        logger.error("No file path provided")
        return False, "No file path specified"

    if not isinstance(report_text, str):
        logger.error("Report text must be a string")
        return False, "Invalid report content type"

    if not report_text.strip():
        logger.error("Report text is empty")
        return False, "Report content is empty"

    try:
        # Create parent directory if needed
        parent_dir = os.path.dirname(file_path)
        if parent_dir and not os.path.exists(parent_dir):
            os.makedirs(parent_dir, exist_ok=True)
            logger.debug(f"Created directory: {parent_dir}")

        # Atomic write: write to temp file, then rename
        fd, temp_path = tempfile.mkstemp(suffix='.tmp', dir=parent_dir or '.')
        try:
            with os.fdopen(fd, 'w', encoding='utf-8') as f:
                f.write(report_text)
            shutil.move(temp_path, file_path)
            logger.info(f"Report saved: {file_path}")
            return True, "Report saved successfully"
        except Exception as e:
            if os.path.exists(temp_path):
                os.remove(temp_path)
            raise

    except IOError as e:
        logger.error(f"File I/O error: {e}")
        return False, f"I/O error: {e}"
    except Exception as e:
        logger.error(f"Save failed: {e}")
        return False, f"Save error: {e}"