# waf_engine.py — Native Python WAF detection
# Identifies WAF vendors via HTTP response headers, cookies, and body patterns.
import urllib.request
import urllib.error
import urllib.parse
import queue
import re

result_queue = queue.Queue()
is_running = False

# ---------------------------------------------------------------------------
# WAF signature database
# Each entry: (label, match_target, pattern)
# match_target: "header:<Name>", "cookie", "body", "status"
# ---------------------------------------------------------------------------

WAF_SIGNATURES = [
    # Cloudflare
    ("Cloudflare",      "header:CF-RAY",               r".+"),
    ("Cloudflare",      "header:Server",                r"(?i)cloudflare"),
    ("Cloudflare",      "body",                         r"(?i)cloudflare ray id"),
    # AWS WAF
    ("AWS WAF",         "header:X-AMZ-CF-ID",           r".+"),
    ("AWS WAF",         "header:x-amzn-RequestId",      r".+"),
    # Akamai
    ("Akamai",          "header:X-Check-Cacheable",     r".+"),
    ("Akamai",          "header:Server",                r"(?i)akamaighost"),
    # Imperva / Incapsula
    ("Imperva/Incapsula","header:X-Iinfo",              r".+"),
    ("Imperva/Incapsula","cookie",                      r"(?i)incap_ses|visid_incap"),
    # F5 BIG-IP ASM
    ("F5 BIG-IP",       "cookie",                       r"(?i)TS[0-9a-f]{8}"),
    ("F5 BIG-IP",       "header:X-WA-Info",             r".+"),
    # ModSecurity
    ("ModSecurity",     "header:Server",                r"(?i)mod_security|modsecurity"),
    ("ModSecurity",     "body",                         r"(?i)mod_security|this error was generated by mod_sec"),
    # Barracuda
    ("Barracuda",       "cookie",                       r"(?i)barra_counter_session"),
    ("Barracuda",       "header:X-Barracuda-Connect",   r".+"),
    # Sucuri
    ("Sucuri",          "header:X-Sucuri-ID",           r".+"),
    ("Sucuri",          "body",                         r"(?i)sucuri website firewall"),
    # Wordfence
    ("Wordfence",       "body",                         r"(?i)generated by wordfence"),
    # Fortinet FortiWeb
    ("FortiWeb",        "header:X-Powered-By-Fortiweb", r".+"),
    ("FortiWeb",        "cookie",                       r"(?i)FORTIWAFSID"),
    # DDoS-Guard
    ("DDoS-Guard",      "header:Server",                r"(?i)ddos-guard"),
    # Fastly
    ("Fastly",          "header:X-Served-By",           r"(?i)cache-"),
    ("Fastly",          "header:Fastly-Debug-Digest",   r".+"),
    # Nginx generic block page
    ("Nginx (generic)", "body",                         r"(?i)nginx.*400 bad request|nginx.*403 forbidden"),
    # Generic WAF block indicators
    ("Generic WAF",     "status",                       r"^(403|406|429|501)$"),
    ("Generic WAF",     "body",                         r"(?i)access denied|blocked by|security policy|your ip|firewall"),
]

# Probe payloads that should trigger a WAF if one is present
TRIGGER_PAYLOADS = [
    "' OR '1'='1",
    "<script>alert(1)</script>",
    "/../../../etc/passwd",
    "UNION SELECT NULL--",
    "; ls -la",
]


def _fetch(url, headers=None, timeout=10):
    req = urllib.request.Request(url, headers=headers or {"User-Agent": "Mozilla/5.0"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.getcode(), dict(resp.headers), resp.read(65536).decode("utf-8", errors="ignore"), dict(resp.headers).get("Set-Cookie", "")
    except urllib.error.HTTPError as e:
        body = ""
        try:
            body = e.read(65536).decode("utf-8", errors="ignore")
        except Exception:
            pass
        return e.code, dict(e.headers), body, dict(e.headers).get("Set-Cookie", "")
    except Exception as exc:
        return None, {}, "", ""


def _match_signatures(status, headers, body, cookie):
    detected = set()
    for label, target, pattern in WAF_SIGNATURES:
        try:
            if target.startswith("header:"):
                hname = target.split(":", 1)[1]
                value = headers.get(hname, "") or headers.get(hname.lower(), "")
                if value and re.search(pattern, value):
                    detected.add(label)
            elif target == "cookie":
                if cookie and re.search(pattern, cookie):
                    detected.add(label)
            elif target == "body":
                if body and re.search(pattern, body):
                    detected.add(label)
            elif target == "status":
                if status and re.search(pattern, str(status)):
                    detected.add(label)
        except Exception:
            continue
    return detected


def run_waf_detection(base_url):
    global is_running
    is_running = True

    result_queue.put(("STATUS", f"Starting WAF detection on {base_url}"))

    # Phase 1: baseline request
    result_queue.put(("STATUS", "Phase 1: Baseline request"))
    status, headers, body, cookie = _fetch(base_url)
    if status is None:
        result_queue.put(("ERROR", f"Could not reach {base_url}"))
        is_running = False
        result_queue.put(("DONE", "WAF detection aborted."))
        return

    result_queue.put(("INFO", f"Baseline: HTTP {status}"))
    baseline_waf = _match_signatures(status, headers, body, cookie)
    for w in baseline_waf:
        result_queue.put(("WARN", f"WAF signature matched on baseline: {w}"))

    if not is_running:
        result_queue.put(("DONE", "WAF detection stopped."))
        return

    # Phase 2: send attack-like probes and watch for WAF block responses
    result_queue.put(("STATUS", "Phase 2: Sending WAF trigger probes"))
    triggered = set()
    for payload in TRIGGER_PAYLOADS:
        if not is_running:
            break
        probe_url = base_url.rstrip("/") + "/?waf_test=" + urllib.parse.quote(payload)
        p_status, p_headers, p_body, p_cookie = _fetch(probe_url)
        if p_status is None:
            continue
        hits = _match_signatures(p_status, p_headers, p_body, p_cookie)
        new_hits = hits - baseline_waf
        for h in new_hits:
            if h not in triggered:
                triggered.add(h)
                result_queue.put(("FAIL", f"WAF triggered by probe '{payload[:30]}': {h}"))
        if p_status in (403, 406, 429, 501) and p_status != status:
            result_queue.put(("WARN", f"Status changed to {p_status} on probe — possible WAF block"))

    # Summary
    all_detected = baseline_waf | triggered
    if all_detected:
        result_queue.put(("FAIL", "WAF DETECTED: " + ", ".join(sorted(all_detected))))
    else:
        result_queue.put(("PASS", "No WAF signatures detected — target may be unprotected"))

    is_running = False
    result_queue.put(("DONE", "WAF detection complete."))


def stop_waf_detection():
    global is_running
    is_running = False
